stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Hello!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


deploy-prod:
  stage: deploy
  script:
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_DEFAULT_BRANCH
    - echo $CI_PIPELINE_SOURCE
  rules:
    - changes:
        - app/**/*
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - app/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true


